In [9]:
import numpy as np

from tensordev import Universal
NumpyCore = Universal(np)

from tensordev.core.utils import assemble_shuffle_algebra

In [10]:
N_sample = 10
a = np.ones((N_sample, 4))

NumpyCore.index_add(a, 1)

In [11]:
sa = assemble_shuffle_algebra(2, 4)
op = sa['operators'][(4,3)]

In [12]:
(d, n, m), (size, rows, cols, data) = op


In [13]:
np.random.seed(123)
u = np.random.uniform(0, 1, 16)
v = np.random.uniform(0, 1, 8)

In [14]:
u[rows]

array([0.69646919, 0.69646919, 0.28613933, ..., 0.39804426, 0.73799541,
       0.73799541], shape=(1368,))

In [15]:
size

array([ 1,  2,  4,  3,  6,  7,  6,  4,  7, 10, 12,  9,  8, 11,  7,  4,  6,
       11, 16, 12, 14, 18, 15,  9,  8, 13, 16, 12,  8, 11,  6,  3,  4,  8,
       15, 11, 16, 21, 18, 11, 12, 20, 23, 18, 16, 21, 13,  7,  6, 11, 18,
       13, 15, 20, 16, 10,  7, 11, 13, 11,  6,  8,  4,  2,  2,  4,  8,  6,
       11, 13, 11,  7, 10, 16, 20, 15, 13, 18, 11,  6,  7, 13, 21, 16, 18,
       23, 20, 12, 11, 18, 21, 16, 11, 15,  8,  4,  3,  6, 11,  8, 12, 16,
       13,  8,  9, 15, 18, 14, 12, 16, 11,  6,  4,  7, 11,  8,  9, 12, 10,
        7,  4,  6,  7,  6,  3,  4,  2,  1])

In [23]:
from tensordev.core.utils.index_add_numba import index_add_numba

a = np.array([[1,2,34,8,1,4]])
idx = np.array([2,0,3,1])

index_add_numba(a, idx)

array([[ 3,  0, 43,  4]])